# Generated by Django 6.0.1 on 2026-01-15 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(help_text='E.g., Italian, Homemade Sweets', max_length=100)),
                ('bio', models.TextField()),
                ('location', models.CharField(help_text='Neighborhood or Zip Code', max_length=100)),
                ('contact_info', models.CharField(help_text='Phone number or email', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='cooks/')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('is_available', models.BooleanField(default=True)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='marketplace.cook')),
            ],
        ),
    ]
