# Generated by Django 6.0.1 on 2026-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When do you want this?', null=True),
        ),
    ]
